//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PrinterScanner
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PrinterDatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PrinterDatabaseEntities object using the connection string found in the 'PrinterDatabaseEntities' section of the application configuration file.
        /// </summary>
        public PrinterDatabaseEntities() : base("name=PrinterDatabaseEntities", "PrinterDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PrinterDatabaseEntities object.
        /// </summary>
        public PrinterDatabaseEntities(string connectionString) : base(connectionString, "PrinterDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PrinterDatabaseEntities object.
        /// </summary>
        public PrinterDatabaseEntities(EntityConnection connection) : base(connection, "PrinterDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Printer> Printers
        {
            get
            {
                if ((_Printers == null))
                {
                    _Printers = base.CreateObjectSet<Printer>("Printers");
                }
                return _Printers;
            }
        }
        private ObjectSet<Printer> _Printers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Printers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrinters(Printer printer)
        {
            base.AddObject("Printers", printer);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PrinterDatabaseModel", Name="Printer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Printer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Printer object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Printer CreatePrinter(global::System.Guid id)
        {
            Printer printer = new Printer();
            printer.ID = id;
            return printer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IpAddress
        {
            get
            {
                return _IpAddress;
            }
            set
            {
                OnIpAddressChanging(value);
                ReportPropertyChanging("IpAddress");
                _IpAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IpAddress");
                OnIpAddressChanged();
            }
        }
        private global::System.String _IpAddress;
        partial void OnIpAddressChanging(global::System.String value);
        partial void OnIpAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MacAddress
        {
            get
            {
                return _MacAddress;
            }
            set
            {
                OnMacAddressChanging(value);
                ReportPropertyChanging("MacAddress");
                _MacAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MacAddress");
                OnMacAddressChanged();
            }
        }
        private global::System.String _MacAddress;
        partial void OnMacAddressChanging(global::System.String value);
        partial void OnMacAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastStatus
        {
            get
            {
                return _LastStatus;
            }
            set
            {
                OnLastStatusChanging(value);
                ReportPropertyChanging("LastStatus");
                _LastStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastStatus");
                OnLastStatusChanged();
            }
        }
        private global::System.String _LastStatus;
        partial void OnLastStatusChanging(global::System.String value);
        partial void OnLastStatusChanged();

        #endregion
    
    }

    #endregion
    
}
